global:
  project: agylam-bot
  ref: "dev"
  isTag: false
  registry: ""

bot:
  image: agylam/bot
  replicas: 1
  ports: {}

postgresql:
  enabled: true
  fullnameOverride: postgres
  commonAnnotations:
    helm.sh/hook: pre-install,pre-upgrade
  auth:
    database: agylam
    username: changeme
    password: changeme

ENV: {}

SECRETS: {}