global:
  project: agylam-bot
  tier: "prod"
  ref: "tag"
  isTag: true

bot:
  image: agylam/bot
  replicas: 1
  ports: {}

postgresql:
  enabled: true
  fullnameOverride: postgres
  commonAnnotations:
    helm.sh/hook: pre-install,pre-upgrade
  auth:
    database: agylam
    username: "{{ PRODUCTION_PGUSER }}"
    password: "{{ PRODUCTION_PGPASSWORD }}"

ENV:
  production:
    PGPORT: "5432"
    PGDATABASE: agylam

SECRETS:
  production:
    DADATA_TOKEN: "{{ DADATA_TOKEN }}"
    TELEGRAM_TOKEN: "{{ PRODUCTION_TELEGRAM_TOKEN }}"
    PGUSER: "{{ PRODUCTION_PGUSER }}"
    PGPASSWORD: "{{ PRODUCTION_PGPASSWORD }}"
    PGHOST: "{{ PRODUCTION_PGHOST }}"
